matrix:
  include:
    - language: scala
      jdk:
        - openjdk8
      script: sh -c 'cd mvn-advent-of-code && mvn clean test'
    - language: scala
      scala:
        - 2.12.8
      script: sh -c 'cd scala-advent-of-code && sbt clean test'
