matrix:
  include:
    - name: Scala
      language: scala
      scala: 2.13.6
      script:
        - sh -c 'cd scala-advent-of-code && sbt test'

    - name: Java
      language: java
      jdk: openjdk13
      script:
        - sh -c 'cd java-advent-of-code && mvn test'

    - name: Kotlin
      language: java
      jdk: openjdk13
      script:
        - sh -c 'cd kotlin-advent-of-code && mvn test' 

    - name: Python
      language: python
      python: 3.8
      script:
        - sh -c 'cd python-advent-of-code && python -m unittest discover -p "*test.py"'

    - name: C++
      language: cpp
      compiler: gcc
      script:
        - sh -c 'cd cpp-advent-of-code && make'

    - name: C-Sharp
      language: csharp
      mono: none
      dotnet: 5.0
      script:
        - sh -c 'cd cpp-advent-of-code && dotnet restore && dotnet build && dotnet test'
