language: scala
jdk:
  - openjdk8
jobs:
  include:
    - stage: Java
      script: sh -c 'cd java-advent-of-code && mvn clean test'
    - stage: Scala
      script: sh -c 'cd scala-advent-of-code && sbt clean test'
