matrix:
  include:
    - name: Scala
      language: scala
      scala: 2.12.2
      script:
        - sh -c 'cd scala-advent-of-code && sbt test'

    - name: Java
      language: java
      jdk: openjdk13
      script:
        - sh -c 'cd java-advent-of-code && mvn test'

    - name: Kotlin
      language: java
      jdk: openjdk13
      script:
        - sh -c 'cd kotlin-advent-of-code && mvn test' 

    - name: C#
      language: csharp
      mono: none
      dotnet: 3.0.100
      script:
        - sh -c 'cd dotnet-advent-of-code && dotnet test'

