matrix:
  include:
    - name: Scala
      language: scala
      scala: 2.12.2
      script:
        - sh -c 'cd scala-advent-of-code && sbt clean test'

    - name: Java
      language: java
      jdk: openjdk13
      script:
        - sh -c 'cd java-advent-of-code && mvn clean test'

    - name: Kotlin
      language: java
      jdk: openjdk13
      script:
        - sh -c 'cd kotlin-advent-of-code && mvn clean test' 

